
services:
  api:
    build: ./API
    container_name: python_api
    develop:
      watch:
        - action: sync+restart
          path: ./API
          target: /app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    networks:
      - PsychNet
  vis:
    build: ./VIS
    container_name: react_vis
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync+restart
          path: ./VIS
          target: /app
    networks:
      - PsychNet
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: ./nginx.conf
          target: /etc/nginx/nginx.conf
    depends_on:
      - api
      - vis
    networks:
      - PsychNet
volumes:
  mongo_data:
networks:
  PsychNet:
    driver: bridge